### LOGIN | ADMIN
POST {{base-url}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "{{password}}"
}

### GET CHARACTER
GET {{base-url}}/characters/3
Authorization: Bearer {{admin-token}}